//32
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("2.0.032.0213")]
[assembly: AssemblyFileVersion("2.0.032.0213")]
[assembly: AssemblyCopyright("Copyright © 2012 - February 2017")]
