//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace FurcadiaFramework_Example.Demo
{


	public class ScriptDemo : IDemo
	{
        #region IDemo Members

        public void Run()
        {
            Console.WriteLine("HELLO WORLD! :)");
        }

        #endregion
    }
}
